### ISSUE TITLE
ERROR: modpost: "sched_numa_hop_mask" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!

### ISSUE THREAD

**Issue by Maximal30** [Frogging-Family/linux-tkg#731]
My OS is Arch Linux x86_64
Please tell me how to fix the error: when compiling kernel 6.3 ERROR: modpost: "sched_numa_hop_mask" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:136: Module.symvers] Error 1
make: *** [Makefile:1980: modpost] Error 2

**Comment by Tk-Glitch** [comment]
You'll want to set `_numadisable="true"` currently when building with Project C. A fix will come soon.

**Comment by Maximal30** [comment]
Thanks for the answer

**Comment by befabry** [comment]
@Tk-Glitch Hello, how do I set `_numadisable="true"` ?

**Comment by deadYokai** [comment]
@befabry in file `customization.cfg` (https://github.com/Frogging-Family/linux-tkg/blob/master/customization.cfg#L148)

**Comment by RyanBlakeIT** [comment]
Will this break nVIDIA drivers?

**Comment by befabry** [comment]
It's already broken for me. No answer from their forums. I have switched to Xorg since 530.43

**Comment by whitehara** [comment]
> My OS is Arch Linux x86_64 Please tell me how to fix the error: when compiling kernel 6.3 ERROR: modpost: "sched_numa_hop_mask" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined! make[1]: *** [scripts/Makefile.modpost:136: Module.symvers] Error 1 make: *** [Makefile:1980: modpost] Error 2

I disabled CONFIG_MLX5_CORE, because I don't use this driver. And this workaround worked fine for me.

**Comment by gardotd426** [comment]
> It's already broken for me. No answer from their forums. I have switched to Xorg since 530.43

@befabry `_numadisable="true"` does a LOT more damage than just messing up Wayland or whatever you're talking about. It completely disables all CUDA *and* NVENC support.

**Comment by ptr1337** [comment]
> > It's already broken for me. No answer from their forums. I have switched to Xorg since 530.43
> 
> @befabry `_numadisable="true"` does a LOT more damage than just messing up Wayland or whatever you're talking about. It completely disables all CUDA _and_ NVENC support.

Why should NUMA affect these things? Makes really zero sense.
https://www.kernel.org/doc/html/v4.18/vm/numa.html

**Comment by ventureoo** [comment]
> > It's already broken for me. No answer from their forums. I have switched to Xorg since 530.43
> 
> @befabry `_numadisable="true"` does a LOT more damage than just messing up Wayland or whatever you're talking about. It completely disables all CUDA _and_ NVENC support.

Not really. For now, CUDA doesn't have a strict dependency on NUMA. This myth has spread because of a bug in the NVIDIA driver because CUDA used to not work without NUMA, but it was fixed a long time ago.

Please see:
https://bugs.gentoo.org/663234#c11
https://forums.developer.nvidia.com/t/please-lift-numa-dependency-of-cuda-or-provide-a-test-for-it-in-the-installer-and-kernel-module/63870

**Comment by ryanmusante** [comment]
So according to the Nvidia developer forum post, it is fixed. And Numa can safely be disabled for those who want.

**Comment by gardotd426** [comment]
>Not really. For now, CUDA doesn't have a strict dependency on NUMA. This myth has spread because of a bug in the NVIDIA driver because CUDA used to not work without NUMA, but it was fixed a long time ago.

I wasn't spreading some myth I've heard, I've actually never heard this outside of the `customization.cfg` for this repo, it flat-out says it breaks CUDA/NVENC. If it doesn't someone needs to file a PR fixing it. I have some shit going on this morning but I'll file one when I get home if no one else has yet.

**Comment by SeongGino** [comment]
For what it's worth, I compiled linux63-pds with NUMA disabled; CUDA and Nvenc do in fact seem to work fine.

So no idea how long this info has been floating around, but maybe it's a good idea to remove the note and set it as default? Or at least adjust the warning to reflect this only affecting some branches of older kernels?

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/b54abe9ba5dbc7cf3cdc3615177e1554c508695a

**Comment by SeongGino** [comment]
Still not fixed:

```
...
  AR      vmlinux.a
  LD      vmlinux.o
vmlinux.o: warning: objtool: hyperv_init+0x40d: unreachable instruction
  OBJCOPY modules.builtin.modinfo
  GEN     modules.builtin
  MODPOST Module.symvers
ERROR: modpost: "sched_numa_hop_mask" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:136: Module.symvers] Error 1
make: *** [Makefile:1980: modpost] Error 2
  DESCEND objtool
  DESCEND bpf/resolve_btfids
make[3]: 'install_headers' is up to date.
make[3]: 'install_headers' is up to date.
  CALL    scripts/checksyscalls.sh
  CHK     kernel/kheaders_data.tar.xz
  MODPOST Module.symvers
ERROR: modpost: "sched_numa_hop_mask" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:136: Module.symvers] Error 1
make: *** [Makefile:1980: modpost] Error 2
```

**Comment by thegamingrestoration** [comment]
Can confirm, same error message as @SeongGino

**Comment by obj-obj** [comment]
I can also confirm, built still fails

**Comment by v1993** [comment]
In the meantime, you can use this config fragment: [disable-mlx5.myfrag.txt](https://github.com/Frogging-Family/linux-tkg/files/11466684/disable-mlx5.myfrag.txt) - drop it in linux-tkg directory and remove `.txt`, then confirm applying it when prompted during build. Haven't tested if new patchset still crashes, though.

**Comment by cr1ogen** [comment]
Give me the error compiling 6.4 kernel

``` 
ERROR: modpost: "sched_numa_hop_mask" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!
make[5]: *** [scripts/Makefile.modpost:136: Module.symvers] Error 1
make[4]: *** [Makefile:1981: modpost] Error 2
make[3]: *** [Makefile:357: __build_one_by_one] Error 2
make[2]: *** [debian/rules:10: build-arch] Error 2
dpkg-buildpackage: fallo: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:139: deb-pkg] Error 2
make: *** [Makefile:1660: deb-pkg] Error 2
 -> exit cleanup done
```

**Comment by obj-obj** [comment]
Same, I just disabled NUMA again

**Comment by ryanmusante** [comment]
I use CFS + Numa. Any negligible gains under custom scheduler isn't worth sacrificing numa

**Comment by obj-obj** [comment]
Isn't NUMA only important for dual-socket systems though?

**Comment by ptr1337** [comment]
> Isn't NUMA only important for dual-socket systems though?

Yeah, correct. Some years ago it was common to disable NUMA on not NUMA supported CPU's since it was possible to yield some more performance if disabled. But this issue got solved years ago.
But if prjc is not able to fix this issue, there should be just forced to disable NUMA at prjc. I don't even know if prjc does properly support numa.

**Comment by ryanmusante** [comment]
Oh, I'm confusing Numa with Cuda. Nevermind
