### ISSUE TITLE
Failure when using winesync/fastsync patch option for 6.8.1 kernel

### ISSUE THREAD

**Issue by s0mebodyhelpme** [Frogging-Family/linux-tkg#904]
**Describe the bug**
 - Which OS do you encounter the bug on?

   Arch Linux

 - A clear and concise description of what the bug is.

    Failure when applying winesync/fastsync patch for 6.8.1 kernel.

 - Attach the contents of your logs folder by drag & dropping each file into this message.
 
 [prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/14623300/prepare.log.txt)

**Comment by bunkbail** [comment]
[winesync.PATCH](https://github.com/Frogging-Family/linux-tkg/files/14809719/winesync.PATCH)

you can try editting the prepare file and use this patch instead. i've removed the documentation patches that causes patching errors (i have no use of the documentation files, and it doesn't functionally affect winesync) and i've also fixed the error in the affected makefile.

**Comment by s0mebodyhelpme** [comment]
Nice. Sounds like something that potentially could be merged. May test this out later.

**Comment by s0mebodyhelpme** [comment]
Sorry for the late reply btw. Was on a trip recently.

**Comment by veganvelociraptor** [comment]
Will this be fixed? It still doesn't work with kernel v6.8.4:

```
### Applying 0007-v6.8-winesync.patch... ###
patching file drivers/misc/Kconfig
Hunk #1 succeeded at 574 with fuzz 2 (offset 78 lines).
patching file drivers/misc/Makefile
Hunk #1 succeeded at 59 with fuzz 1 (offset 1 line).
patching file drivers/misc/winesync.c
patching file Documentation/admin-guide/devices.txt
patching file Documentation/userspace-api/ioctl/ioctl-number.rst
Hunk #1 succeeded at 378 (offset 3 lines).
patching file drivers/misc/winesync.c
patching file include/linux/miscdevice.h
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file Documentation/userspace-api/index.rst
Hunk #1 FAILED at 29.
1 out of 1 hunk FAILED -- saving rejects to file Documentation/userspace-api/index.rst.rej
patching file Documentation/userspace-api/winesync.rst
patching file tools/testing/selftests/Makefile
Hunk #1 FAILED at 14.
1 out of 1 hunk FAILED -- saving rejects to file tools/testing/selftests/Makefile.rej
patching file tools/testing/selftests/drivers/winesync/Makefile
patching file tools/testing/selftests/drivers/winesync/config
patching file tools/testing/selftests/drivers/winesync/winesync.c
patching file tools/testing/selftests/drivers/winesync/winesync.c
patching file tools/testing/selftests/drivers/winesync/winesync.c
patching file tools/testing/selftests/drivers/winesync/winesync.c
patching file tools/testing/selftests/drivers/winesync/winesync.c
patching file tools/testing/selftests/drivers/winesync/winesync.c
patching file tools/testing/selftests/drivers/winesync/winesync.c
patching file MAINTAINERS
Hunk #1 succeeded at 23703 with fuzz 2 (offset 1783 lines).
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file tools/testing/selftests/drivers/winesync/winesync.c
patching file tools/testing/selftests/drivers/winesync/winesync.c
patching file tools/testing/selftests/drivers/winesync/winesync.c
patching file tools/testing/selftests/drivers/winesync/winesync.c
patching file Documentation/userspace-api/winesync.rst
patching file drivers/misc/winesync.c
patching file include/uapi/linux/winesync.h
patching file tools/testing/selftests/drivers/winesync/winesync.c
patching file tools/testing/selftests/drivers/winesync/winesync.c
patching file Documentation/userspace-api/winesync.rst
```

**Comment by veganvelociraptor** [comment]
> Patch doesn't work for me. I pointed it to the file but it still failed.

Yep, this part fails for me as well:
```
patching file tools/testing/selftests/Makefile
Hunk #1 FAILED at 14.
1 out of 1 hunk FAILED -- saving rejects to file tools/testing/selftests/Makefile.rej
```

**Comment by ptr1337** [comment]
You could simply use winesync-dkms from the AUR. That makes it way less complicated, specially because patching fastsync into the kernel tree requires currently some extra packaging steps. (I think they are used by TKG)

**Comment by ptr1337** [comment]
https://github.com/Frogging-Family/linux-tkg/pull/917

Ive sent a PR here.
